version: "3.2"

services:

  web:
    image: library/node:8-alpine
    working_dir: /code
    volumes:
      - .:/code
    networks:
      - proxy
    ports:
      - 9090:9090
    environment:
      VIRTUAL_HOST: abibao.platform.127.0.0.1.xip.io
      VIRTUAL_PORT: 9090
      LETSENCRYPT_HOST: abibao.platform.127.0.0.1.xip.io
      LETSENCRYPT_EMAIL: team@abibao.com
      REACT_APP_ADMIN_URL: http://abibao.platform.127.0.0.1.xip.io
      REACT_APP_API_URL: http://abibao.api.127.0.0.1.xip.io
      REACT_APP_GOOGLE_AUTH_URL: http://abibao.api.127.0.0.1.xip.io/auth/google/callback
    volumes:
      - .:/code
    command: "yarn run start"

networks:
  proxy:
    external:
      name: communs_default
