version: "2"

services:

  admin:
    image: library/node:6-alpine
    working_dir: /code
    volumes:
      - .:/code
    environment:
      NODE_ENV: development
      REACT_APP_ADMIN_URL: https://admin.platform.abibao.com.local.net
      REACT_APP_API_URL: https://api.platform.abibao.com.local.net
      REACT_APP_GOOGLE_AUTH_URL: https://api.platform.abibao.com.local.net/auth/google/callback
    command: "tail -F -n0 /etc/hosts"
    networks:
      proxy:
        ipv4_address: 172.45.0.30

networks:
  proxy:
    external:
      name: development_infra
